Quick fix for an issue (bug in the JRE?) where Class.forName() sometimes throws a NoClassDefFoundError instead of ClassNotFoundException.
git-svn-id: https://svn.neo4j.org/components@5423 0b971d98-bb2f-0410-8247-b05b2b5feb2a